source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform:ios,'7.0'

target 'MSMarksButtonList_Example', :exclusive => true do
  pod 'MSMarksButtonList', :path => '../'
end

target 'MSMarksButtonList_Tests', :exclusive => true do
  pod 'MSMarksButtonList', :path => '../'

  
end
